require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/capture_pokemons", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # CapturePokemon. As you add validations to CapturePokemon, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      CapturePokemon.create! valid_attributes
      get capture_pokemons_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      capture_pokemon = CapturePokemon.create! valid_attributes
      get capture_pokemon_url(capture_pokemon)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_capture_pokemon_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      capture_pokemon = CapturePokemon.create! valid_attributes
      get edit_capture_pokemon_url(capture_pokemon)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CapturePokemon" do
        expect {
          post capture_pokemons_url, params: { capture_pokemon: valid_attributes }
        }.to change(CapturePokemon, :count).by(1)
      end

      it "redirects to the created capture_pokemon" do
        post capture_pokemons_url, params: { capture_pokemon: valid_attributes }
        expect(response).to redirect_to(capture_pokemon_url(CapturePokemon.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CapturePokemon" do
        expect {
          post capture_pokemons_url, params: { capture_pokemon: invalid_attributes }
        }.to change(CapturePokemon, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post capture_pokemons_url, params: { capture_pokemon: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested capture_pokemon" do
        capture_pokemon = CapturePokemon.create! valid_attributes
        patch capture_pokemon_url(capture_pokemon), params: { capture_pokemon: new_attributes }
        capture_pokemon.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the capture_pokemon" do
        capture_pokemon = CapturePokemon.create! valid_attributes
        patch capture_pokemon_url(capture_pokemon), params: { capture_pokemon: new_attributes }
        capture_pokemon.reload
        expect(response).to redirect_to(capture_pokemon_url(capture_pokemon))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        capture_pokemon = CapturePokemon.create! valid_attributes
        patch capture_pokemon_url(capture_pokemon), params: { capture_pokemon: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested capture_pokemon" do
      capture_pokemon = CapturePokemon.create! valid_attributes
      expect {
        delete capture_pokemon_url(capture_pokemon)
      }.to change(CapturePokemon, :count).by(-1)
    end

    it "redirects to the capture_pokemons list" do
      capture_pokemon = CapturePokemon.create! valid_attributes
      delete capture_pokemon_url(capture_pokemon)
      expect(response).to redirect_to(capture_pokemons_url)
    end
  end
end
