default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: exam_one_2023_development

  
test:
  <<: *default
  database: base_project_2023_test


production:
  <<: *default
  database: exam_one_2023_production
  username: exam_one_2023
  password: <%= ENV["BASE_PROJECT_2023_DATABASE_PASSWORD"] %>
